sustainability_keywords = [
    # Financial Statements
    "Balance Sheet",
    "Income Statement",
    "Cash Flow Statement",
    "Consolidated Financial Statements",
    "Statement of Operations",
    "Comprehensive Income",
    "Profit and Loss",
    "Revenue Breakdown",
    "Operating Expenses",
    "Deferred Revenue",
    "Net Income",
    "Gross Profit",
    "Impairment Loss",
    "Assets and Liabilities",
    "Earnings Before Interest and Taxes (EBIT)",
    "Earnings Per Share (EPS)",
    "Financial Ratios",
    "Debt to Equity Ratio",
    "Liquidity Ratio",
    "Accounts Receivable",
    "Accounts Payable",
    "Inventory Turnover",
    "Equity Statement",
    "Fixed Assets",
    "Current Liabilities",
    "Non-Current Liabilities",
    "Shareholder Equity",
    "Annual Financial Report",
    "Quarterly Financial Report",

    # Environmental and Sustainability
    "Sustainability Report",
    "Carbon Emissions",
    "Net Zero",
    "Environmental Impact",
    "Corporate Social Responsibility (CSR)",
    "ESG Metrics",
    "Renewable Energy",
    "Energy Efficiency",
    "Waste Management",
    "Water Usage",
    "Sustainable Sourcing",
    "Climate Goals",
    "Greenhouse Gas Emissions",
    "Sustainability Initiatives",
    "Biodiversity Impact",
    "Sustainable Packaging",
    "Circular Economy",
    "Energy Transition",
    "Carbon Footprint",
    "Climate Resilience",
    "Environmental Compliance",
    "Resource Efficiency",
    "Recyclable Materials",
    "Low Carbon Strategy",
    "Decarbonization Goals",
    "Clean Energy Investment",
    "Sustainable Development Goals (SDGs)",

    # Operational Performance
    "Key Metrics",
    "Revenue Recognition",
    "Capital Expenditures",
    "Merchant Solutions",
    "Subscription Solutions",
    "Logistics Operations",
    "Operating Margin",
    "Free Cash Flow",
    "Return on Investment",
    "Customer Acquisition Cost (CAC)",
    "Customer Lifetime Value (CLTV)",
    "Churn Rate",
    "Operational Excellence",
    "Supply Chain Management",
    "Productivity Metrics",
    "Cost of Goods Sold (COGS)",
    "Business Continuity",
    "Scalability Metrics",
    "Employee Retention Rate",
    "Operational Risk Management",

    # General Governance and Compliance
    "Audit Report",
    "Risk Management",
    "Internal Controls",
    "Critical Audit Matters",
    "Legal Contingencies",
    "Governance Structure",
    "Corporate Policies",
    "Code of Conduct",
    "Compliance Programs",
    "Anti-Bribery and Corruption",
    "Whistleblower Policy",
    "Board Composition",
    "Executive Compensation",
    "Diversity and Inclusion",
    "Corporate Governance",
    "Compliance Certification",
    "Data Privacy",
    "Cybersecurity",
    "Regulatory Compliance",

    # Stakeholder and Market Relations
    "Shareholder Report",
    "Market Trends",
    "Strategic Partnerships",
    "Investor Relations",
    "Growth Projections",
    "Stakeholder Engagement",
    "Community Impact",
    "Public Policy",
    "Media Relations",
    "Brand Equity",
    "Corporate Identity",
    "Corporate Sponsorships",
    "Dividend Policy",
    "Stock Performance",
    "Shareholder Meetings",
    "Investor Presentations",
    "Earnings Calls",
    "Analyst Reports",

    # Footnotes and Additional Context
    "Notes to Financial Statements",
    "Non-GAAP Measures",
    "Depreciation and Amortization",
    "Tax Liabilities",
    "Deferred Tax Assets",
    "Stock-Based Compensation",
    "Impairment of Assets",
    "Revenue Reconciliation",
    "Operational Footnotes",
    "Capital Allocation",
    "Goodwill Impairment",
    "Accounting Policies",
    "Depreciation Schedule",
    "Credit Ratings",

    # Industry and Market Context
    "Market Segments",
    "Revenue by Geography",
    "Revenue Growth",
    "Customer Demographics",
    "Sector Performance",
    "Emerging Markets",
    "Industry Benchmarks",
    "Competitive Analysis",
    "Market Opportunities",
    "Regulatory Changes",
    "Global Trends",
    "Trade Tariffs",
    "Market Share",

    # Additional Metrics and Indicators
    "Key Performance Indicators (KPIs)",
    "Environmental, Social, and Governance (ESG)",
    "Sustainability KPIs",
    "Social Impact",
    "Philanthropy",
    "Workforce Metrics",
    "Employee Engagement",
    "Community Investments",
    "Supplier Responsibility",
    "Human Rights",
    "Labor Practices",
    "Health and Safety",
    "Workplace Diversity",
    "Training and Development",
    "Employee Wellbeing",
    "Customer Satisfaction",
    "Net Promoter Score (NPS)",
    "Social Equity",
    "Philanthropic Contributions"
]
